services:
  es3ewt-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: es3ewt
    volumes:
      - ./es3ewt-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  es3ewt-minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - "./minio-data:/var/lib/minio/data"

  es3ewt-api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.api.yaml
    ports:
      - "8080:8080"
    depends_on:
      - es3ewt-db
      - es3ewt-minio
    environment:
      CONNECTION_STRING: postgresql://postgres:postgres@es3ewt-db:5432/es3ewt
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: es3ewt
      POSTGRES_HOST: es3ewt-db
      POSTGRES_PORT: 5432
      PORT: 8080
      JWT_SECRET: "superSecret"
      JWT_EXPIRATION: "1h"
      MINIO_ENDPOINT: es3ewt-minio
    volumes:
      - ../packages/api:/app/packages/api
      - ../packages/core:/app/packages/core
